### ISSUE TITLE
Crash with 12 bands instead of 10

### ISSUE THREAD

**Issue by cmosig** [linlei1214/SITS-Former#4]
I am running the following configuration: 
```
python3 ./sits_former_git/code/pretraining.py --dataset_path 'dataset' --pretrain_path 'pretraining' --num_workers 8 --valid_rate 0.03 --max_length 200 --patch_size 5 --num_features 12 --mask_rate 0.3 --epochs 200 --batch_size 16 --hidden_size 256 --layers 3 --attn_heads 8 --learning_rate 1e-3 --warmup_epochs 10 --decay_gamma 0.99 --dropout 0.1 --gradient_clipping 5.0 --with_cuda
```

If I run this configuration with `--num_features 10` with your data everything works fine. If I run this configuration with `--num-features 12` and my own data, which has twelve bands, the following error occurs: 

```
Traceback (most recent call last):
  File "/net/home/cmosig/projects/tree_mortality/main_pipeline/C_sits_former/./sits_former_git/code/pretraining.py", line 181, in <module>
    train_loss, valida_loss = trainer.train(epoch)
                              ^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/projects/tree_mortality/main_pipeline/C_sits_former/sits_former_git/code/trainer/pretrain.py", line 58, in train
    mask_prediction = self.model(data["bert_input"].float(),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/projects/tree_mortality/main_pipeline/C_sits_former/sits_former_git/code/model/predition_model.py", line 24, in forward
    x = self.bert(x, doy, mask)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/projects/tree_mortality/main_pipeline/C_sits_former/sits_former_git/code/model/bert.py", line 37, in forward
    x = self.embedding(input_sequence=x, doy_sequence=doy)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/projects/tree_mortality/main_pipeline/C_sits_former/sits_former_git/code/model/embedding/bert.py", line 61, in forward
    obs_embed = self.linear(obs_embed.view(first_dim, -1))   # [batch_size*seq_length, embed_size]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/cmosig/venv/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3200x256 and 128x256)
```  

Here is a sample file of the patches I supplied the model with:
[patch_01_10_2021_644490_5767010_uavforsat_CFB910_644490_5767110.zip](https://github.com/linlei1214/SITS-Former/files/13043855/patch_01_10_2021_644490_5767010_uavforsat_CFB910_644490_5767110.zip)

**Comment by cmosig** [comment]
The argument `--num_features` seems to be passed through but then ignored when configuring the BERT embedding: https://github.com/linlei1214/SITS-Former/blob/f58e56259621dfff90f27822d31341778440272b/code/model/embedding/bert.py#L15

**Comment by linlei1214** [comment]
You are right. Please modify it according to your understanding. You can resize channel_size with num_features  and choose appropriate kernel_size.


Lei Lin
2023-10-22
On 10/19/2023 22:36，Clemens ***@***.***> wrote：

The argument --num_features seems to be passed through but then ignored when configuring the BERT embedding: https://github.com/linlei1214/SITS-Former/blob/f58e56259621dfff90f27822d31341778440272b/code/model/embedding/bert.py#L15

**Comment by cmosig** [comment]
> You are right. Please modify it according to your understanding. You can resize channel_size with num_features and choose appropriate kernel_size.

Happy to submit a pull request. What is your intended way of resizing the 3D kernel relative to the number of bands?
